### ISSUE TITLE
Finalize automatic uploading

### ISSUE THREAD

**Issue by cemachelen** [cemac/AgroClimatic-Monitor#46]
Automatic uploading 

1. Move to standard format file naming
2. Add filename pattern check so erroneous dates aren't added to h5s
3. set chron job for 00.00 brazil time or 5am uk time
 * Check is new files in any upload folder if so trigger preprocessing
 * Load anaconda env and run NewData.py picking up new tiffs
 * unload anaconda env and load pip env run batch municipalities script

Would be nice:  To add last updated stamp at bottom of page

**Comment by Murilodsv** [comment]
Thanks for creating this separated issue. 

Just a side note, Marcelo Zeri asked if the updating could be any how more frequent so that they wouldnt have to wait until next day to know if things worked fine. 

Maybe, additionally to the cron, if a button could be create to trigger the preprocessing besides the uploading button should work? What do you think? Please feel free to decide whatever works best.
